name: CI Workflow

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7' 

      - name: Find and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Find all requirements.txt files and install dependencies for each
          for req_file in $(find . -name "requirements.txt"); do
            echo "Installing dependencies from $req_file"
            pip install -r "$req_file"
          done

      - name: Run Tests
        run: |
          # Run tests in each subproject that contains tests
          for test_dir in $(find . -type d -name "tests"); do
            echo "Running tests in $test_dir"
            pytest "$test_dir"
          done
